[tool.isort]
# Black compatible values for isort https://black.readthedocs.io/en/stable/compatible_configs.html#isort
profile = "black"
multi_line = 3

[tool.pytest.ini_options]
addopts = "-v --tb=short --cov=rasterriskassessmentplugin"
testpaths = [
    "tests"
]

[tool.coverage.report]
omit = ["rasterriskassessmentplugin/qgis_plugin_tools/*"]
